import { notFound } from 'next/navigation'
import { getSharedEmergencyCard } from '@/services/document-generator'
import { PublicCardClient } from './client'

type Props = {
  params: Promise<{ slug: string }>
}

export default async function PublicEmergencyCardPage({ params }: Props) {
  const { slug } = await params
  const cardData = await getSharedEmergencyCard(slug)

  if (!cardData) {
    notFound()
  }

  return (
    <div
      className="min-h-screen bg-neutral-50"
      style={{ fontFamily: "'Plus Jakarta Sans', 'DM Sans', system-ui, sans-serif" }}
    >
      {/* Top Bar */}
      <header className="bg-white border-b border-neutral-200 px-4 py-3">
        <div className="max-w-2xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-red-600 flex items-center justify-center text-white">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
              </svg>
            </div>
            <span className="text-sm font-semibold text-neutral-900">HeartGuard</span>
          </div>
          <span className="text-xs text-neutral-400">Emergency Medical Card</span>
        </div>
      </header>

      {/* Card */}
      <main className="px-4 py-6">
        <PublicCardClient data={cardData} />
      </main>

      {/* Footer */}
      <footer className="px-4 py-6 text-center">
        <p className="text-xs text-neutral-400 max-w-md mx-auto">
          This card was generated by HeartGuard, an AI-powered medication safety tool for Long QT Syndrome patients.
          This is a reference document — always consult the patient&apos;s cardiologist for treatment decisions.
        </p>
      </footer>
    </div>
  )
}
